### ISSUE TITLE
porcelain.push doesn't check for shared ancestry (i.e. defaults to --force)

### ISSUE THREAD

**Issue by brvier** [dulwich/dulwich#494]
Creating a new repository, commiting one file, then doing a Porcelain.push erase the whole remote repository.

Is that an expected behavior ?

**Comment by khertan** [comment]
Certainly badly :) Version is last git release. I'll send a minimal example.Benoît HERVIER - http://khertan.netLe 23 janv. 2017 17:50, Jelmer Vernooĳ <notifications@github.com> a écrit :What version of Dulwich? How are you invoking porcelain.push?

**Comment by khertan** [comment]
Here is how i use it :
https://gist.github.com/khertan/db40b60c2f67b51935993b40cfb568a9

**Comment by jelmer** [comment]
Hmm, that doesn't look wrong at a first glance. What is the observed behaviour exactly? Do the refs on the remote repo disappear? What kind of remote repo are you working with?

**Comment by khertan** [comment]
All history is erased on server, the remote repository is a self hosted:
nginx + git-http-backend + git + gitweb
I will try with a other backend, indeed.

**Comment by jelmer** [comment]
On Tue, Jan 24, 2017 at 07:22:36AM -0800, Benoît HERVIER wrote:
> All history is erased on server, the remote repository is a self hosted:
> nginx + git-http-backend + git + gitweb
> I will try with a other backend, indeed.
When you say that history is erased, do you mean that the other refs are
removed or rather than the history that's pushed is not appended to the remote
history for refs/heads/master?

**Comment by khertan** [comment]
Sorry, I m not a git expert :)Git log on remote server show me that the commit history wasnt append.Benoît HERVIER - http://khertan.netLe 24 janv. 2017 17:16, Jelmer Vernooĳ <notifications@github.com> a écrit :On Tue, Jan 24, 2017 at 07:22:36AM -0800, Benoît HERVIER wrote:
> All history is erased on server, the remote repository is a self hosted:
> nginx + git-http-backend + git + gitweb
> I will try with a other backend, indeed.
When you say that history is erased, do you mean that the other refs are
removed or rather than the history that's pushed is not appended to the remote
history for refs/heads/master?

**Comment by jelmer** [comment]
Yes, that's correct since you forcible overwrite what's on the server. You probably want to pull down changes first.

Note that the remote changes aren't really erased - see 'git reflog' on the remote server - the refs/heads/master ref just points at a new commit that has no other history.

**Comment by khertan** [comment]
But if i pull before, I erase local commits not yet sent to remote. Or I should pull in a temporary branch to do a manual merge ?Benoît HERVIER - http://khertan.netLe 24 janv. 2017 18:44, Jelmer Vernooĳ <notifications@github.com> a écrit :Yes, that's correct since you forcible overwrite what's on the server. You probably want to pull down changes first.
Note that the remote changes aren't really erased - see 'git reflog' on the remote server - the refs/heads/master ref just points at a new commit that has no other history.

**Comment by jelmer** [comment]
On Tue, Jan 24, 2017 at 10:06:30AM -0800, Benoît HERVIER wrote:
> But if i pull before, I erase local commits not yet sent to remote. Or I should pull in a temporary branch to do a manual merge 
Yeah, you probably want to do a pull, then do the autocommit on top of the just pulled in change, then push.
