### ISSUE TITLE
porcelain.push() does not update remote refs

### ISSUE THREAD

**Issue by frans-fuerst** [dulwich/dulwich#752]
When I do the following:
```
repo = repo.Repo(working_directory)
remote_url = repo.get_config().get(("remote", "origin"), "url").decode()
porcelain.push(repo, remote_url, 'master')
```
I would expect `origin/master` and `origin/HEAD` being set to local `master` but it isn't. When I run
```
git push
```
in the working directory, the refs get updated.
Is this intended behaviour? In that case: how would I `push` like `git push` does?

**Comment by jelmer** [comment]
Are you pushing any new objects? If not, then this may be an instance of #739

**Comment by alvyjudy** [comment]
I have the same issue too when trying to push the change of one repo to another on my local machine. The problem seems to exist at the ``send_pack`` method of a respective client. In my case, ``push`` calls the ``LocalGitClient`` (in ``client.py`` file) which seems to be missing the necessary code to update the ``refs`` on the repository.

**Comment by alvyjudy** [comment]
It appears that it is just the ``push`` function that is missing the implementation to update ``refs/remotes/`` and I'm wondering if it would be a good idea to add to it? Something like the reverse of the ``fetch`` function:


    1294    r.refs.import_refs(

    1295           b'refs/remotes/' + remote_name, branches, message=message,

    1296           prune=prune)
