### ISSUE TITLE
No git repository

### ISSUE THREAD

**Issue by alchem1ster** [dulwich/dulwich#920]
**Dulwich version:** both 0.20.25 and https://github.com/dulwich/dulwich/commit/1f66817d712e3563ce1ff53b1218491a2eae39da
**OS version:** Windows 10 21H2 19044.1415

```
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import dulwich.porcelain
>>> dulwich.porcelain.clone("https://github.com/dulwich/dulwich", "./TEST")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "O:\Python38\lib\site-packages\dulwich\porcelain.py", line 444, in clone
    with open_repo_closing(source) as r:
  File "O:\Python38\lib\site-packages\dulwich\porcelain.py", line 215, in open_repo_closing
    return closing(Repo(path_or_repo))
  File "O:\Python38\lib\site-packages\dulwich\repo.py", line 1059, in __init__
    raise NotGitRepository(
dulwich.errors.NotGitRepository: No git repository was found at https://github.com/dulwich/dulwich
```

**Comment by pmrowla** [comment]
This was broken in 6d51e8a71b48c3e52fc0eef54cf96d9712ce8eff

```
https://github.com/dulwich/dulwich/blob/1f66817d712e3563ce1ff53b1218491a2eae39da/dulwich/porcelain.py#L444-L452
```
This will fail if `source` is a URL since the source `Repo` object can't be created.

The reason for having the standalone `do_clone` method from https://github.com/dulwich/dulwich/pull/851 was because of this. In `Repo.clone(self, ...)` we know we are already cloning from a local repo instance, but for `porcelain.clone` we have to support remote URLs (where we can't instantiate a `Repo(source_url)` object to then call `source.clone(...)` from).

@jelmer

**Comment by pmrowla** [comment]
6d51e8a also does not pass the depth and errstream args from `porcelain.clone` into `Repo.clone`
